version: '3'
 
services:
  proxy:
    build:
      context: ./infrastructure/nginx
      args:
        - SITE_DOMAIN=test.adarich.com
    depends_on:
      - certbot
    volumes:
      - letsencrypt_certs:/etc/nginx/certs
      - letsencrypt_www:/var/www/letsencrypt
    links:
      # change to however we want to proxy it
      - app:test.adarich.com
    ports:
      - "8000:80"
      - "4430:443"
    restart: always

  certbot:
    build:
      context: ./infrastructure/certbot
      args:
        - SITE_DOMAIN=test.adarich.com
    command: /bin/true
    volumes:
      - letsencrypt_certs:/etc/letsencrypt
      - letsencrypt_www:/var/www/letsencrypt

  app:
    build:
      context: .
      args:
        - SITE_DOMAIN=test.adarich.com
    restart: always
 
volumes:
  letsencrypt_certs: ~
  letsencrypt_www: ~
