version: 2
jobs:
  build_and_push_image:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "DOCKER TAG ${echo "pr-${CI_PULL_REQUEST##*/}}"
      - run: docker info
      - run: docker build . --tag jamesrichford/jamesadarich.com:${DOCKER_IMAGE_TAG:-latest} --build-arg SITE_DOMAIN=james.adarich.com --rm=false
      # - run: docker run -d -p 8080:8080 jamesrichford/jamesadarich.com:${DOCKER_IMAGE_TAG:-latest}
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push jamesrichford/jamesadarich.com:${DOCKER_IMAGE_TAG:-latest}
  browser_tests:
    docker:
      - image: node:8
    steps:
      # simple check to make sure the server started
      # could do with some lovely selenium tests at some point
      # - run: apt-get install curl
      # - run: curl --retry 10 --retry-delay 5 -v http://localhost:8080
      - run: echo "run some browser tests"
  static_analysis:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm install
      - run: npm test
  tidy_up:
    docker:
      - image: node:8
    steps:
      - run: echo 'export DOCKER_IMAGE_TAG=$(echo "${CI_PULL_REQUEST##*/}")' >> $BASH_ENV
      - run: echo "DELETE DOCKER TAG ${DOCKER_IMAGE_TAG}"

workflows:
  version: 2
  continuous_integration:
    jobs:
      - static_analysis
      - build_and_push_image:
          filters:
            branches:
              only:
                - master          
#      - browser_tests:
#          requires:
#            - build_and_push_image
#      - qa_approval:
#          type: approval
#          requires:
#            - browser_tests
#            - static_analysis
#          filters:
#            branches:
#]              ignore:
#                - master
      - tidy_up:
          requires:
            - qa_approval
          filters:
            branches:
              ignore:
                - master
