version: 2
jobs:
  build_image:
    machine: true
    steps:
      - checkout
      - run: docker info
      - run: docker build . --tag jamesrichford/jamesadarich.com:latest --build-arg SITE_DOMAIN=james.adarich.com --rm=false
  end_to_end_test:
    machine: true
    steps:
      - run: docker info
      - run: docker run -d -p 8080:8080 jamesrichford/jamesadarich.com:latest; sleep 10
      - run: curl --retry 10 --retry-delay 5 -v http://localhost:8080
  push_image:
    machine: true
    steps:
      - run: docker info
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push jamesrichford/jamesadarich.com:latest
  static_analysis:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  continuous_integration:
    jobs:
      - static_analysis
      - build_image
      - end_to_end_test:
        requires:
          - build_image
